# Generated by Django 5.2.1 on 2025-05-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("culture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidite", models.FloatField(blank=True, null=True)),
                ("ph", models.FloatField(blank=True, null=True)),
                ("co2", models.FloatField(blank=True, null=True)),
                ("niveau_eau", models.FloatField(blank=True, null=True)),
                ("lumiere", models.FloatField(blank=True, null=True)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="culture.culture",
                    ),
                ),
            ],
        ),
    ]
