# Generated by Django 5.2.1 on 2025-05-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("culture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapteurType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Capteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capteurs",
                        to="culture.culture",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capteurs.capteurtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CapteurStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_seen", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=20,
                    ),
                ),
                (
                    "capteur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capteurs.capteur",
                    ),
                ),
            ],
        ),
    ]
