# Generated by Django 3.1.12 on 2025-05-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='capteurstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='capteurtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
