# Generated by Django 3.2.19 on 2025-05-11 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culture', '0003_auto_20250511_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to=settings.AUTH_USER_MODEL),
        ),
    ]
